#Site settings
title: codeyh.github.io
author:
  name: Codey Holland
  email: codeyh@gmail.com
description: "Testing GitHub Pages and Jekyll"

#Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
